=== JustinWalk/Lab07/Lab07.dtd
<!ELEMENT Master (Days, Timeslots, Courses)>

<!ELEMENT Days (DayBookings*)>
<!ELEMENT Timeslots (TimeslotBookings*)>
<!ELEMENT Courses (CourseBookings*)>

<!ELEMENT DayBookings (Day, DayBooking*)>
<!ELEMENT TimeslotBookings (Timeslot, TimeslotBooking*)>
<!ELEMENT CourseBookings (Course, CourseBooking*)>

<!ELEMENT Day (#PCDATA)>

<!ELEMENT Timeslot (#PCDATA)>

<!ELEMENT Course (#PCDATA)>

<!ELEMENT DayBooking (Timeslot, Course, Instructor, Activity, Room)>
<!ELEMENT TimeslotBooking (Day, Course, Instructor, Activity, Room)>
<!ELEMENT CourseBooking (Day, Timeslot, Instructor, Activity, Room)>

<!ELEMENT Instructor (#PCDATA)>

<!ELEMENT Activity (#PCDATA)>

<!ELEMENT Room (#PCDATA)>

=== JustinWalk/Lab07/Lab07.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schedule SYSTEM "Lab07.dtd">

<Master>
    <Days>
        <DayBookings>
            <Day> "Monday" </Day>
            <DayBooking>
                <Timeslot> "13:30" </Timeslot>
                <Course> "ACIT4770" </Course>
                <Instructor>Trevor Lord</Instructor>
                <Activity>Lab</Activity>
                <Room>SE12-306</Room>
            </DayBooking>
            <DayBooking>
                <Timeslot> "14:30" </Timeslot>
                <Course> "ACIT4770" </Course>
                <Instructor>Trevor Lord</Instructor>
                <Activity>Lab</Activity>
                <Room>SE12-306</Room>
            </DayBooking>
            <DayBooking>
                <Timeslot> "15:30" </Timeslot>
                <Course> "ACIT4910" </Course>
                <Instructor>Richard Chau</Instructor>
                <Activity>Lecture</Activity>
                <Room>SW9-206</Room>
            </DayBooking>
            <DayBooking>
                <Timeslot> "16:30" </Timeslot>
                <Course> "ACIT4650" </Course>
                <Instructor>Medhat Elmasry</Instructor>
                <Activity>Lecture</Activity>
                <Room>SE6-205</Room>
            </DayBooking>
        </DayBookings>

        <DayBookings>
            <Day> "Tuesday" </Day>
            <DayBooking>
                <Timeslot> "10:30" </Timeslot>
                <Course> "ACIT4620" </Course>
                <Instructor>Bethany Edmunds</Instructor>
                <Activity>Lab</Activity>
                <Room>SE12-306</Room>
            </DayBooking>
            <DayBooking>
                <Timeslot> "11:30" </Timeslot>
                <Course> "ACIT4620" </Course>
                <Instructor>Bethany Edmunds</Instructor>
                <Activity>Lab</Activity>
                <Room>SE12-306</Room>
            </DayBooking>
            <DayBooking>
                <Timeslot> "12:30" </Timeslot>
                <Course> "ACIT4650" </Course>
                <Instructor>Medhat Elmasry</Instructor>
                <Activity>Lecture</Activity>
                <Room>SW9-206</Room>
            </DayBooking>
            <DayBooking>
                <Timeslot> "13:30" </Timeslot>
                <Course> "ACIT4650" </Course>
                <Instructor>Medhat Elmasry</Instructor>
                <Activity>Lab</Activity>
                <Room>SE12-306</Room>
            </DayBooking>
            <DayBooking>
                <Timeslot> "14:30" </Timeslot>
                <Course> "ACIT4650" </Course>
                <Instructor>Medhat Elmasry</Instructor>
                <Activity>Lab</Activity>
                <Room>SE12-306</Room>
            </DayBooking>
            <DayBooking>
                <Timeslot> "15:30" </Timeslot>
                <Course> "ACIT4620" </Course>
                <Instructor>Bethany Edmunds</Instructor>
                <Activity>Lecture</Activity>
                <Room>SW3-3615</Room>
            </DayBooking>
            <DayBooking>
                <Timeslot> "16:30" </Timeslot>
                <Course> "ACIT4620" </Course>
                <Instructor>Bethany Edmunds</Instructor>
                <Activity>Lecture</Activity>
                <Room>SW3-3615</Room>
            </DayBooking>
        </DayBookings>

        <DayBookings>
            <Day> "Wednesday" </Day>
            <DayBooking>
                <Timeslot> "10:30" </Timeslot>
                <Course> "ACIT4660" </Course>
                <Instructor>Steve Frabiszewski</Instructor>
                <Activity>Lab</Activity>
                <Room>SE12-306</Room>
            </DayBooking>
            <DayBooking>
                <Timeslot> "11:30" </Timeslot>
                <Course> "ACIT4660" </Course>
                <Instructor>Steve Frabiszewski</Instructor>
                <Activity>Lab</Activity>
                <Room>SE12-306</Room>
            </DayBooking>
            <DayBooking>
                <Timeslot> "12:30" </Timeslot>
                <Course> "ACIT4850" </Course>
                <Instructor>James Parry</Instructor>
                <Activity>Lecture</Activity>
                <Room>SW3-1750</Room>
            </DayBooking>
            <DayBooking>
                <Timeslot> "13:30" </Timeslot>
                <Course> "ACIT4850" </Course>
                <Instructor>James Parry</Instructor>
                <Activity>Lecture</Activity>
                <Room>SW3-1750</Room>
            </DayBooking>
        </DayBookings>

        <DayBookings>
            <Day> "Thursday" </Day>
            <DayBooking>
                <Timeslot> "9:30" </Timeslot>
                <Course> "ACIT4910" </Course>
                <Instructor>Richard Chau</Instructor>
                <Activity>Lecture</Activity>
                <Room>SW5-1840</Room>
            </DayBooking>
            <DayBooking>
                <Timeslot> "10:30" </Timeslot>
                <Course> "ACIT4850" </Course>
                <Instructor>James Parry</Instructor>
                <Activity>Lab</Activity>
                <Room>SE12-320</Room>
            </DayBooking>
            <DayBooking>
                <Timeslot> "11:30" </Timeslot>
                <Course> "ACIT4850" </Course>
                <Instructor>James Parry</Instructor>
                <Activity>Lab</Activity>
                <Room>SE12-320</Room>
            </DayBooking>
            <DayBooking>
                <Timeslot> "13:30" </Timeslot>
                <Course> "ACIT4910" </Course>
                <Instructor>Richard Chau</Instructor>
                <Activity>Lab</Activity>
                <Room>SE12-306</Room>
            </DayBooking>
            <DayBooking>
                <Timeslot> "14:30" </Timeslot>
                <Course> "ACIT4910" </Course>
                <Instructor>Richard Chau</Instructor>
                <Activity>Lab</Activity>
                <Room>SE12-306</Room>
            </DayBooking>
        </DayBookings>

        <DayBookings>
            <Day> "Friday" </Day>
            <DayBooking>
                <Timeslot> "8:30" </Timeslot>
                <Course> "ACIT4660" </Course>
                <Instructor>Steve Frabiszewski</Instructor>
                <Activity>Lecture</Activity>
                <Room>SW9-206</Room>
            </DayBooking>
            <DayBooking>
                <Timeslot> "9:30" </Timeslot>
                <Course> "ACIT4660" </Course>
                <Instructor>Steve Frabiszewski</Instructor>
                <Activity>Lecture</Activity>
                <Room>SW9-206</Room>
            </DayBooking>
        </DayBookings>
    </Days>
</Master>
